version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: proa_user
      POSTGRES_PASSWORD: proa_password
      POSTGRES_DB: proa_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
